version: "3"

x-addon: &addon
  build:
    context: ../
    dockerfile: ./dockerfiles/Dockerfile.dev
    args:
      ADDON_NAME: "${ADDON_NAME}"
      ADDON_PATH: "${ADDON_PATH}"
      VOLTO_VERSION: ${VOLTO_VERSION:-16}
  volumes:
    - ${CURRENT_DIR}:/app/src/addons/${ADDON_PATH}/
  environment:
    RAZZLE_INTERNAL_API_PATH: http://backend-acceptance:55001/plone
    RAZZLE_API_PATH: http://localhost:55001/plone
    HOST: 0.0.0.0
  tty: true
  profiles:
    - dev

services:

  addon-dev:
    <<: *addon
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      - backend-acceptance

  addon-acceptance:
    build:
      context: ../
      dockerfile: ./dockerfiles/Dockerfile.acceptance
      args:
        ADDON_NAME: "${ADDON_NAME}"
        ADDON_PATH: "${ADDON_PATH}"
        VOLTO_VERSION: ${VOLTO_VERSION:-16}
    volumes:
      - ${CURRENT_DIR}:/app/src/addons/${ADDON_PATH}/
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend-acceptance:55001/plone
      RAZZLE_API_PATH: http://localhost:55001/plone
      HOST: 0.0.0.0
    ports:
      - 3000:3000
    depends_on:
      - backend-acceptance
    profiles:
      - prod

  backend-acceptance:
    image: plone/server-acceptance:${PLONE_VERSION:-6}
    ports:
      - 55001:55001
    profiles:
      - dev
      - prod
