version: "3"

x-addon: &addon
  build:
    context: ../
    dockerfile: ./dockerfiles/Dockerfile.dev
    args:
      ADDON_NAME: "${ADDON_NAME}"
      ADDON_PATH: "${ADDON_PATH}"
      VOLTO_VERSION: ${VOLTO_VERSION:-16}
  volumes:
    - ${CURRENT_DIR}:/app/src/addons/${ADDON_PATH}/
  environment:
    RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
    RAZZLE_API_PATH: http://localhost:8080/Plone
    HOST: 0.0.0.0
  tty: true
  profiles:
    - dev

services:

  addon-dev:
    <<: *addon
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      - backend

  addon-no-backend:
    <<: *addon

  addon-storybook:
    <<: *addon
    volumes:
      - ${CURRENT_DIR}:/app/src/addons/${ADDON_PATH}/
      - ${CURRENT_DIR}/.storybook:/app/storybook-static/
    ports:
      - 6006:6006
    command: "storybook"

  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    environment:
      CORS_ALLOW_ORIGIN: '*'
    ports:
      - 8080:8080
    profiles:
      - dev
