name: Code analysis checks
on:
  - push

env:
  node-version: 18.x

jobs:

  codeanalysis:
    runs-on: ubuntu-latest
    steps:
      - name: Main checkout
        uses: actions/checkout@v3

      - name: Linting
        run: make lint
