name: Unit Tests
on:
  - push

env:
  node-version: 18.x

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - name: Main checkout
        uses: actions/checkout@v3

      - name: Unit tests
        run: make test-ci
